/**
 * Created by dingyiming on 2017/6/2.
 */

module.exports={
    'PAGE_LOGIN':'PAGE_LOGIN',
    'PAGE_PLATFORM':'PAGE_PLATFORM',
    'PAGE_PASSWORDFORGET':'PAGE_PASSWORDFORGET',
    'UPDATE_PAGE_STATE':'UPDATE_PAGE_STATE',
    'UPDATE_NAVIGATOR':'UPDATE_NAVIGATOR'
}
